name: 'dartintro'
version: 0.1.0
description: An old school intro for Dartpad.
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  web: ^0.5.0
dev_dependencies:
  build_web_compilers: ^4.0.10
  build_runner: ^2.4.11
  lints: ^4.0.0